site_name: tortilla-spec
repo_url: https://github.com/csaybar/tortilla-spec
site_url: https://csaybar.github.io/tortilla-spec
site_description: A simple python format to storage files.
site_author: Cesar Aybar
edit_uri: edit/main/docs/
repo_name: csaybar/tortilla-spec
copyright: Maintained by <a href="https://csaybar.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/csaybar/tortilla-spec
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tortilla-spec

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
