docs_dir: .
site_name: tortilla-spec

site_url: https://github.com/tacofoundation/tortilla-python
site_description: A simple python format to storage files.
site_author: Cesar Aybar


copyright: Maintained by <a href="https://csaybar.com">Florian</a>.

repo_url: https://github.com/tacofoundation/tortilla-python
repo_name: tacofoundation/tortilla-python
# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: '#d49f0c'
      accent: '#d49f0c'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/tortilla.png
  favicon: assets/images/tortilla.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide   


extra_css:
  - ./docs/style.css

# Page tree
nav:
  - Home: 
    - README.md
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md
    - Code of conduct: CODE_OF_CONDUCT.md
  # - Functions: 
  #   - ./docs/FUNCTIONS.md
  #   - Query metadata: ./docs/Functions/query_metadata.md
  #   - Process Image: ./docs/Functions/process_image.md
  #   - Download Data: ./docs/Functions/download_data.md
  # - Processes: 
  #   - ./docs/PROCESSES.md
  #   - Recursion: ./docs/Process/recursion.md
  #   - Concurrency: ./docs/Process/concurrency.md
  #   - Parallelism: ./docs/Process/parallelism.md
  #   - Difference: ./docs/Process/difference.md
  # - Comparation:
  #   - ./docs/COMPARATION.md
  #   - Get: ./docs/Comparation/eedatagetPixels.md
  #   - Compute: ./docs/Comparation/eedatacomputePixels.md
  #   - Comparison: ./docs/Comparation/comparison.md
  #   - Conclusion: ./docs/Comparation/conclusion.md

# Plugins
plugins:
  - search
  - same-dir
  - mkdocstrings 
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist